spring:
  profiles:
    active: 'win'

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    #driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://207.211.170.50:3306/SpaceX
    username: root
    password: 123456
#    dynamic:
#      primary: cms
#      strict: true
#      datasource:
#        cms:
#          driver-class-name: org.postgresql.Driver
#          url: jdbc:postgresql://localhost:5432/cms
#          username: postgres
#          password: 123456
#        camunda:
#          driver-class-name: org.postgresql.Driver
#          url: jdbc:postgresql://localhost:5432/camunda
#          username: postgres
#          password: 123456

# 日志配置
logging:
  level:
    com.lq: debug
  file:
    path: ../SpaceX/logs
#    org.springframework: info

#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: lidar

# MyBatis配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.lq.spacex.**.domain

#datasource:
#  primary:
#    driver-class-name: org.postgresql.Driver
#    jdbc-url: jdbc:postgresql://localhost:5432/cms
#    username: postgres
#    password: 123456
#  secondary:
#    driver-class-name: org.postgresql.Driver
#    jdbc-url: jdbc:postgresql://localhost:5432/camunda
#    username: postgres
#    password: 123456
#camunda:
#  bpm:
#    auto-deployment-enabled: false
#    job-execution:
#      enabled: false
#    database:
#      schema-update: 'false'

